<?php

namespace AppBundle\Repository;

/**
 * airportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class airportRepository extends \Doctrine\ORM\EntityRepository
{
}
