<?php

namespace AppBundle\Repository;

/**
 * flightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class flightRepository extends \Doctrine\ORM\EntityRepository
{
}
