<?php

namespace AppBundle\Repository;

/**
 * tripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tripRepository extends \Doctrine\ORM\EntityRepository
{
}
